name: Test Plugin

on:
  push:
    branches:
      - '*v'

jobs:
  build_and_package:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      id-token: write 
      checks: write
      packages: write
      repository-projects: write
      security-events: write
      statuses: write
      

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate runner context data
        run: |
          ./platform

      - name: Show
        run: |
          cat ./runner-context.json
