name: Release Canary Backend

on:
  push:
    branches:
      - '*'

jobs:
  build_and_package:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      id-token: write 

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Chainloop
        run: |
          curl -sfL https://dl.chainloop.dev/cli/install.sh | bash -s -- --with-platform-plugin

      - name: Gather runner context data
        run: |
          chainloop gather-runner-context --runner-token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Show runner context data
        run: |
          cat ./runner-context.json

      - name: Add runner context material to attestation
        run: |
          chainloop att add --value ./runner-context.json
