name: Test Plugin

on:
  push:
    branches:
      - '*'

jobs:
  build_and_package:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      id-token: write 


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build plugin
        run: |
          pwd

      - name: Show runner context data
        run: |
          ./platform
